version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
  pre_build:
    commands:
      - pip install --upgrade awscli
      - aws --version
      - pip install virtualenv
      - virtualenv /tmp/venv
      - . /tmp/venv/bin/activate
      - pip install -r requirements.txt
      - pip install chalice
      - export PYTHONPATH=.
      - chalice package packaged
  build:
    commands:
      - echo  "Build stage..."
      - aws cloudformation package --template-file packaged/sam.json --output-template-file transformed.yaml
  post_build:
    commands:
      - echo "Post build stage..."
      - echo Build completed on `date`
artifacts:
  type: zip
  files:
    - transformed.yaml
